2022-09-19 00:38:04,494 INFO: Microblog startup [in /home/zozo/PycharmProjects/microblog/app/__init__.py:44]
2022-09-19 00:38:29,077 ERROR: Exception on /user/susan [GET] [in /home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/zozo/PycharmProjects/microblog/app/routes.py", line 80, in user
    return render_template("user.html", user=user, posts=posts,
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/zozo/PycharmProjects/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/zozo/PycharmProjects/microblog/app/templates/base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "/home/zozo/PycharmProjects/microblog/app/templates/user.html", line 22, in block 'content'
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2022-09-19 00:40:08,362 INFO: Microblog startup [in /home/zozo/PycharmProjects/microblog/app/__init__.py:44]
2022-09-19 00:41:44,444 INFO: Microblog startup [in /home/zozo/PycharmProjects/microblog/app/__init__.py:44]
2022-09-19 15:37:57,749 INFO: Microblog startup [in /home/zozo/PycharmProjects/microblog/app/__init__.py:44]
2022-09-19 20:37:15,112 INFO: Microblog startup [in /home/zozo/PycharmProjects/microblog/app/__init__.py:46]
2022-09-19 20:39:47,362 INFO: Microblog startup [in /home/zozo/PycharmProjects/microblog/app/__init__.py:46]
2022-09-19 20:49:12,965 INFO: Microblog startup [in /home/zozo/PycharmProjects/microblog/app/__init__.py:46]
2022-09-19 20:54:25,746 INFO: Microblog startup [in /home/zozo/PycharmProjects/microblog/app/__init__.py:46]
2022-09-19 20:54:51,640 INFO: Microblog startup [in /home/zozo/PycharmProjects/microblog/app/__init__.py:46]
2022-09-19 20:55:17,629 INFO: Microblog startup [in /home/zozo/PycharmProjects/microblog/app/__init__.py:46]
2022-09-19 20:55:51,264 INFO: Microblog startup [in /home/zozo/PycharmProjects/microblog/app/__init__.py:46]
2022-09-19 20:58:44,692 INFO: Microblog startup [in /home/zozo/PycharmProjects/microblog/app/__init__.py:46]
2022-09-19 20:59:16,168 INFO: Microblog startup [in /home/zozo/PycharmProjects/microblog/app/__init__.py:46]
2022-09-19 20:59:28,271 ERROR: Exception on /user/susan [GET] [in /home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/zozo/PycharmProjects/microblog/app/routes.py", line 74, in user
    posts = user.posts.order_by(Post.timestamp.desc()).paginate(
AttributeError: 'function' object has no attribute 'posts'
2022-09-19 21:00:38,557 INFO: Microblog startup [in /home/zozo/PycharmProjects/microblog/app/__init__.py:46]
2022-09-19 21:10:12,875 INFO: Microblog startup [in /home/zozo/PycharmProjects/microblog/app/__init__.py:46]
2022-09-19 21:21:53,408 INFO: Microblog startup [in /home/zozo/PycharmProjects/microblog/app/__init__.py:47]
2022-09-19 21:50:32,362 INFO: Microblog startup [in /home/zozo/PycharmProjects/microblog/app/__init__.py:46]
2022-09-19 21:51:14,470 INFO: Microblog startup [in /home/zozo/PycharmProjects/microblog/app/__init__.py:46]
2022-09-19 21:51:25,423 ERROR: Exception on /user/susan [GET] [in /home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/zozo/PycharmProjects/microblog/app/routes.py", line 74, in user
    posts = user.posts.order_by(Post.timestamp.desc()).paginate(
AttributeError: 'function' object has no attribute 'posts'
2022-09-20 09:54:44,153 INFO: Microblog startup [in /home/zozo/PycharmProjects/microblog/app/__init__.py:46]
2022-09-20 11:13:18,176 INFO: Microblog startup [in /home/zozo/PycharmProjects/microblog/app/__init__.py:46]
2022-09-20 11:17:04,314 INFO: Microblog startup [in /home/zozo/PycharmProjects/microblog/app/__init__.py:46]
2022-09-20 11:17:18,252 ERROR: Exception on /reset_password_request [POST] [in /home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/zozo/PycharmProjects/microblog/app/routes.py", line 154, in reset_password_request
    send_password_reset_email(user)
  File "/home/zozo/PycharmProjects/microblog/app/email.py", line 14, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/home/zozo/PycharmProjects/microblog/app/models.py", line 61, in get_reset_password_token
    return jwt.encode(
AttributeError: module 'jwt' has no attribute 'encode'
2022-09-20 11:28:08,030 INFO: Microblog startup [in /home/zozo/PycharmProjects/microblog/app/__init__.py:46]
2022-09-20 11:28:21,731 ERROR: Exception on /reset_password_request [POST] [in /home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zozo/PycharmProjects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/zozo/PycharmProjects/microblog/app/routes.py", line 154, in reset_password_request
    send_password_reset_email(user)
  File "/home/zozo/PycharmProjects/microblog/app/email.py", line 14, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/home/zozo/PycharmProjects/microblog/app/models.py", line 61, in get_reset_password_token
    return jwt.encode(
AttributeError: 'str' object has no attribute 'decode'
2022-09-20 11:30:59,953 INFO: Microblog startup [in /home/zozo/PycharmProjects/microblog/app/__init__.py:46]
