2022-09-14 20:33:04,719 ERROR: Exception on /index [GET] [in C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\bluin\PycharmProjects\microblog\app\routes.py", line 36, in index
    return render_template("index.html", title="Home", posts=posts)
  File "C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\bluin\PycharmProjects\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\bluin\PycharmProjects\microblog\app\templates\base.html", line 35, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\bluin\PycharmProjects\microblog\app\templates\index.html", line 6, in block 'content'
    {{ form.post.hidden_tag() }}
  File "C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2022-09-14 20:33:11,606 ERROR: Exception on /index [GET] [in C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\bluin\PycharmProjects\microblog\app\routes.py", line 36, in index
    return render_template("index.html", title="Home", posts=posts)
  File "C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\bluin\PycharmProjects\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\bluin\PycharmProjects\microblog\app\templates\base.html", line 35, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\bluin\PycharmProjects\microblog\app\templates\index.html", line 6, in block 'content'
    {{ form.post.hidden_tag() }}
  File "C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2022-09-14 20:33:14,772 ERROR: Exception on /index [GET] [in C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\bluin\PycharmProjects\microblog\app\routes.py", line 36, in index
    return render_template("index.html", title="Home", posts=posts)
  File "C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\bluin\PycharmProjects\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\bluin\PycharmProjects\microblog\app\templates\base.html", line 35, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\bluin\PycharmProjects\microblog\app\templates\index.html", line 6, in block 'content'
    {{ form.post.hidden_tag() }}
  File "C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2022-09-14 20:34:26,446 INFO: Microblog startup [in C:\Users\bluin\PycharmProjects\microblog\app\__init__.py:44]
2022-09-14 20:34:28,259 ERROR: Exception on / [GET] [in C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\bluin\PycharmProjects\microblog\app\routes.py", line 36, in index
    return render_template("index.html", title="Home", posts=posts)
  File "C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\bluin\PycharmProjects\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\bluin\PycharmProjects\microblog\app\templates\base.html", line 35, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\bluin\PycharmProjects\microblog\app\templates\index.html", line 6, in block 'content'
    {{ form.post.hidden_tag() }}
  File "C:\Users\bluin\PycharmProjects\microblog\venv\lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2022-09-14 20:35:12,499 INFO: Microblog startup [in C:\Users\bluin\PycharmProjects\microblog\app\__init__.py:44]
